name: screwdriver
description: A dart package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 0.1.0
homepage: https://github.com/birjuvachhani/screwdriver

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  characters: ^1.0.0

dev_dependencies:
  effective_dart: ^1.2.4
  test: ^1.15.3
