name: screwdriver
description: A dart package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 1.2.0
homepage: https://github.com/birjuvachhani/screwdriver

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  characters: ^1.0.0
  meta: ^1.2.3
  intl: ^0.16.1

dev_dependencies:
  effective_dart: ^1.2.4
  test: ^1.15.4
  test_coverage: ^0.4.3
  mockito: ^4.1.3
